# Numpy

In [18]:
import numpy as np

<br/>
<br/>
<br/>
<br/>

#### Q1) 아래 리스트를 이용하여 1차원 배열을 생성하세요.
  - [103, 815, 571, 934, 599, 945,  71, 669, 639, 116, 423, 985, 814, 506, 792, 295, 914, 397, 654,  32, 859, 321, 850, 340, 325]

In [19]:
# code here
arr1 = np.array([103, 815, 571, 934, 599, 945, 71, 669, 639, 116, 423, 985, 814, 506, 792, 295, 914, 397, 654, 32, 859, 321, 850, 340, 325])
arr1

array([103, 815, 571, 934, 599, 945,  71, 669, 639, 116, 423, 985, 814,
       506, 792, 295, 914, 397, 654,  32, 859, 321, 850, 340, 325])

#### Q2) arr1의 shape을 5행 5열로 변경하여 arr2에 저장하세요.
 - reshape

In [20]:
# code here
arr2 = arr1.reshape(5,5)
arr2

array([[103, 815, 571, 934, 599],
       [945,  71, 669, 639, 116],
       [423, 985, 814, 506, 792],
       [295, 914, 397, 654,  32],
       [859, 321, 850, 340, 325]])

<br/>
<br/>

#### Q3) arr2의 요소 중 71에 10을 곱하세요.
 - 인덱싱/불리언 인덱싱 및 수정

In [21]:
# code here
arr2[arr2 == 71] *= 10
arr2

array([[103, 815, 571, 934, 599],
       [945, 710, 669, 639, 116],
       [423, 985, 814, 506, 792],
       [295, 914, 397, 654,  32],
       [859, 321, 850, 340, 325]])

<br/>
<br/>

#### Q4) arr2의 요소 중 가운데 위치한 9개 요소 (3개 행과 3개 열)을 출력하세요.
 - 슬라이싱

In [22]:
# code here
arr2[1:4, 1:4]

array([[710, 669, 639],
       [985, 814, 506],
       [914, 397, 654]])

<br/>
<br/>

#### Q5) arr2의 요소 중 가운데 위치한 9개 요소에 10을 곱하세요.
 - 슬라이싱 및 수정

In [23]:
# code here
arr2[1:len(arr2)-1, 1:len(arr2)-1] *= 10
arr2

array([[ 103,  815,  571,  934,  599],
       [ 945, 7100, 6690, 6390,  116],
       [ 423, 9850, 8140, 5060,  792],
       [ 295, 9140, 3970, 6540,   32],
       [ 859,  321,  850,  340,  325]])

<br/>
<br/>

#### Q6) arr2의 요소 중 1000 이상인 요소만 추출하여 형태를 3행 3열로 변경한 후 출력하세요.
 - 불리언 인덱싱, reshape

In [24]:
# code here
arr2[arr2>=1000].reshape(3,3)

array([[7100, 6690, 6390],
       [9850, 8140, 5060],
       [9140, 3970, 6540]])

<br/>
<br/>

#### Q7) arr2의 중앙에 있는 값을 -1로 변경한 후 출력하세요.

In [25]:
# code here
arr2[len(arr2)//2, len(arr2)//2] = -1
arr2

array([[ 103,  815,  571,  934,  599],
       [ 945, 7100, 6690, 6390,  116],
       [ 423, 9850,   -1, 5060,  792],
       [ 295, 9140, 3970, 6540,   32],
       [ 859,  321,  850,  340,  325]])

<br/>
<br/>

#### Q8) arr2의 열 별(행과 행) 평균과 표준편차를 출력하세요.

In [26]:
# code here
arr2.mean(axis=0)

array([ 525. , 5445.2, 2416. , 3852.8,  372.8])

In [27]:
arr2.std(axis=0)

array([ 325.37486074, 4086.27827736, 2544.80891228, 2682.34661444,
        286.79986053])

<br/>
<br/>

#### Q9) arr2의 행 별(열과 열) 평균과 표준편차를 출력하세요.

In [30]:
# code here
arr2.mean(axis=1)

array([ 604.4, 4248.2, 3224.8, 3995.4,  539. ])

In [32]:
arr2.std(axis=1)
print(arr2.std(axis=1))

[ 284.79297744 3055.11586687 3779.83118142 3531.12002628  257.69827318]


<br/>
<br/>

#### Q10)  arr2의 요소 중 1000 미만인 요소는 -1으로, 1000 이상인 요소는 arr2의 값을 유지하여 arr3에 저장하세요.

In [33]:
# code here
arr3 = np.where(arr2 < 1000, -1, arr2)
arr3

array([[  -1,   -1,   -1,   -1,   -1],
       [  -1, 7100, 6690, 6390,   -1],
       [  -1, 9850,   -1, 5060,   -1],
       [  -1, 9140, 3970, 6540,   -1],
       [  -1,   -1,   -1,   -1,   -1]])

<br/>
<br/>

#### Q11) arr3의 열 별(행과 행) 평균을 출력하세요

In [34]:
# code here
arr3.mean(axis=0)

array([-1.0000e+00,  5.2176e+03,  2.1314e+03,  3.5976e+03, -1.0000e+00])

<br/>
<br/>

#### Q12) arr3의 전체 평균을 출력하세요.

In [35]:
# code here
arr3.mean()

2188.92

#### Q13) arr3의 요소 중 음수인 요소는 0으로, 나머지 요소는 arr3의 값을 유지하여 arr4에 저장하세요.

In [36]:
# code here
arr4 = np.where(arr3 < 0, 0, arr3)
arr4

array([[   0,    0,    0,    0,    0],
       [   0, 7100, 6690, 6390,    0],
       [   0, 9850,    0, 5060,    0],
       [   0, 9140, 3970, 6540,    0],
       [   0,    0,    0,    0,    0]])

# 완진탐색 모의 문제 + 해설

## [Q1]<br />
arr2 중에서 평균이 500 이상인 열은 값을 그대로, 500 미만인 열은 값을 0으로 변경해 arr1에 저장하려고 한다. <br />해당 작업을 수행하기 위한 올바른 코드는?

[1] arr1= np.where(arr2.mean(axis=0)>=500,0,arr2) <br />
[2] arr1 = np.where(arr2.mean(axis=0)>=500,arr2,0) <br />
[3] arr1 = np.where(arr2.mean(axis=1)>=500,arr2,0) <br />
[4] arr1 = arr2[arr2.mean(axis=0)>=500, arr2, 0] <br />
[5] arr1 = arr2[arr2.mean(axis=0)>=500, 0, arr2]

답: [2]

[해설] <br />
np.where(조건, [x, y])
조건 : arr2.mean(axis=0)>=500 => 같은 열에 있는(axis=0) 값의 평균이 500 이상 <br />
x : 조건에 만족할 경우 지정할 값 <br />
y : 조건에 만족하지 않을 경우 지정할 값 <br />

## [Q2]
0으로 채워진 nxn 행렬에 양 대각선 (x자 형태로)만 1로 채우려고 한다.<br />
이때, (1), (2)에 들어갈 코드가 알맞게 조합된 것을 고르시오.

In [ ]:
# 실행 X
import numpy as np

n=int(input())
arr = np.__(1)__(n)
arr[__(2)__] = 1

print(arr)

[1] (1)-unit, (2)-np.arange(arr.size), np.arange(arr.size - 1, -1, -1) <br />
[2] (1)-eye, (2)-np.arange(arr.size), np.arange(arr.size, -1, -1) <br />
[3] (1)-unit, (2)-np.arange(arr.shape[0]), np.arange(arr.shape[0], 0, -1) <br />
[4] (1)-eye, (2)-np.arange(arr.shape[0]), np.arange(arr.shape[0] - 1, -1, -1) <br />
[5] (1)-unit, (2)-np.arange(arr.shape[0]), np.arange(arr.shape[0] - 1, -1, -1)

In [57]:
import numpy as np

n=4
arr = np.eye(3)
arr[np.arange(arr.shape[0]), np.arange(arr.shape[0] - 1, -1, -1)] = 1

array([[1., 0., 1.],
       [0., 1., 0.],
       [1., 0., 1.]])

np.arange(start, end, step) => start: 시작값(포함), end: 종료 값(포함X), step: 간격
* arr[np.arange(arr.shape[0]), => 0행, 1행, 2행을 의미
* arr[, np.arange(arr.shape[0] -1, -1, -1)] => arr[, [2, 1, 0]] => 2열, 1열, 0열을 의미
=> arr[[0,1,2], [2,1,0]] = 1